### PR TITLE
limit input to 50 chars

### LINKED ISSUE #20: Limit number of characters in input
An enhancement was proposed to limit the number of characters that can be entered in the input field. When this is done, the maximum number of characters should also be shown. There is a good chance that Android already provides a lot of this functionality

### PR DESCRIPTION
**Pull request by emieldesmidt**
Limit the proposal input to 50 chars max, to prevent someone proposing the entire Java in Two Semesters Textbook by Aaron Kans and Quentin Charatan

closes #20

### CODE REVIEW

**Comment by PraveshMoelchand** [comment]
As with previous PRs, let's merge the oldest open PR(#38 )first before merging this one

**Comment by KoningR** [comment]
Works fine as a GUI fix; do note that the voting protocol still allows arbitrarily large texts.

**Comment by erwinvanthiel** [comment]
Works like a charm!

**Comment by PraveshMoelchand** [comment]
I assume the two comments above are approvals. Ready to merge!

**Pull request merged**
