### PR TITLE
Voting complete gui

### LINKED ISSUE #23: Badge when the voting on a proposal has been completed
It has been proposed to add a badge in the top-right corner of the proposal cards in the main screen to indicate that voting on the corresponding proposal has been completed

The solution of this issue will be similar to #22

### PR DESCRIPTION
**Pull request by erwinvanthiel**
proposal blocks now contain a progress bar that indicates to what extent the vote is been completed, basically just a percentage of completeness.
closes #23 
co-authored by: @KoningR and myself.

### CODE REVIEW

**Comment by emieldesmidt** [comment]
Looks really great! I think this is a nice addition to the app :)
As this pr includes commits belonging to the other pr, I'd like to close that one first.

**Comment by PraveshMoelchand** [comment]
> 
> 
> Looks really great! I think this is a nice addition to the app :)
> As this pr includes commits belonging to the other pr, I'd like to close that one first.

I agree!

**Comment by PraveshMoelchand** [comment]
Also, threshold voting causes exactly the same behaviour as described above

**Comment by erwinvanthiel** [comment]
@pravesh, I think the error you are describing might be caused by something else. What happens when you toggle votingmode twice and then respond with a no-vote?

Moreover, I think a threshold voteblock not responding to a no-vote is correct functionality because the progress in that case is defined as a the ratio between yes-votes and required yes-votes.
That being said, I think the bug you encountered is due to both votes being of type threshold, perhaps due to a bug residing in the toggle.

**Comment by PraveshMoelchand** [comment]
Yes, I agree. I do think we need to indicate when everyone has voted on a threshold proposal, but this is something we can fix in another branch/PR.

**Comment by PraveshMoelchand** [comment]
If you don’t get to it, I’ll have a look this weekend what’s going wrong at the moment

**Comment by erwinvanthiel** [comment]
Aah I understand what is going wrong now. Yes we need to fill the progressbar of a thresholdblock when all voters have voted indeed. Ill fix it, no problem.

**Pull request merged**
