### PR TITLE
Threshold casting

### PR DESCRIPTION
**Pull request by emieldesmidt**
I noticed that it was still possible to cast a no / yes on a treshold mode vote. Now the user is only provided the cancel or agree mode, and the displayed info is now also dependent on the mode.

Threshold:
image

Yes/no
image

### CODE REVIEW

**Comment by PraveshMoelchand** [comment]
I am seeing some strange behaviour, this is probably due to the votecompleteness checker. What is happening:
- Peer A creates threshold proposal
- Peer B votes AGREE
- Proposal is complete, 'Final result' is shown
- Peer A is still able to vote, which is not undesired behaviour
- If we now check the proposal info it says 'Current tally'

I'll implement fix in the next commit, please review!

**Comment by PraveshMoelchand** [comment]
Also, I suppose we're going to merge https://github.com/emieldesmidt/trustchain-superapp/pull/38 first, so I'll resolve the merge conflicts by pulling `new-indicator` into this one

**Comment by emieldesmidt** [comment]
Solid fix @PraveshMoelchand, looks all good to me now

**Comment by erwinvanthiel** [comment]
Works fine!

**Pull request merged**
